### PR TITLE
[topcrash_bad_severity] Add a missing field

### LINKED ISSUE #2003: KeyError: 'history' in the topcrash_bad_severity tool
```
2023-04-21 12:01:01,835 - ERROR - Tool topcrash_bad_severity
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 762, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 680, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 454, in get_bugs
    timeout=self.get_config("bz_query_timeout"),
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/bugzilla.py", line 176, in wait
    self.wait_bugs()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/bugzilla.py", line 187, in wait_bugs
    r.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 708, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/bugzilla.py", line 552, in __bugs_cb
    self.bughandler.handle(bug)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/handler.py", line 15, in handle
    self.handler(*args)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 342, in bughandler
    if self.handle_bug(bug, data) is None:
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/topcrash_bad_severity.py", line 37, in handle_bug
    if utils.is_keywords_removed_by_autonag(bug, ["topcrash", "topcrash-startup"]):
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 762, in is_keywords_removed_by_autonag
    for entry in bug["history"]
KeyError: 'history'
```

### PR DESCRIPTION
**Pull request by suhaibmujahid**
Fixes #2003 

## Checklist

- [ ] Type annotations added to new functions
- [ ] Docs added to functions touched in main classes
- [x] Dry-run produced the expected results
- [ ] The [`to-be-announced`](https://github.com/mozilla/relman-auto-nag/labels/to-be-announced) tag added if this is worth announcing

### CODE REVIEW

**Comment by suhaibmujahid** [comment]
# Dry-run

<p>The following bugs have topcrash as keyword but the severity isn't high enough:
<table style="border:1px solid black;border-collapse:collapse;" border="1">
<thead>
<tr>
<th>Bug</th><th>Summary</th>
</tr>
</thead>
<tbody>
<tr bgcolor="#E0E0E0">
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1471720">1471720</a>
</td>
<td>
XPCOM/XPConnect should do a &#34;canary&#34; load of the async shutdown service (Was: fast startup crash in ServiceWorkerRegistrar::ProfileStarted)
</td>
</tr>
<tr >
<td>
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=602102">602102</a>
</td>
<td>
Crash in [@ NS_TableDrivenQI]
</td>
</tr>
</tbody>
</table>
</p>

**Comment by marco-c** [comment]
Bug 602102 seems to be a case which is no longer topcrash, could we do something to filter it out?

We should definitely at least ignore it because the severity was decreased very recently and after the topcrash keyword was set

**Comment by suhaibmujahid** [comment]
> Bug 602102 seems to be a case which is no longer topcrash, could we do something to filter it out?

Yes, I think the needinfo here will add noise and unlikely will change the severity of the bug. 

> We should definitely at least ignore it because the severity was decreased very recently and after the topcrash keyword was set, but maybe there's also some other filter we could apply to ignore these cases (e.g. check if it is still topcrash? or do we already do that?)

All the cases catched by this tool will have their severities decreased/set recently and after adding the topcrash keyword. We already needinfo for low severity when we add the topcrash keyword: https://github.com/mozilla/relman-auto-nag/blob/7c11d39d17872f144f455dbefa6799ba58be6120/auto_nag/scripts/topcrash_add_keyword.py#L89-L107

This tool was added a long time before having the `topcrash_add_keyword` tool. I think we could safely drop this tool if we don't want to needinfo on recently decreased/set severity.

**Comment by marco-c** [comment]
Doesn't this tool also catch cases where the `topcrash` keyword is added by a human and not the bot?

**Comment by suhaibmujahid** [comment]
> Doesn't this tool also catch cases where the `topcrash` keyword is added by a human and not the bot?

Yes, it does. We can make `topcrash_add_keyword` catch that as well since it already does all other filterings.

**Comment by marco-c** [comment]
Moving all topcrash-related responsibilities in a single script makes sense to me!

**Comment by suhaibmujahid** [comment]
Closing in favour of https://github.com/mozilla/bugbot/pull/2022

**Pull request closed without merging**
